Shery.imageEffect(".imagesss", {
  style: 6,
  // debug: true,
  gooey: true,
  config: {
    noiseDetail: { value: 4.58, range: [0, 100] },
    distortionAmount: { value: 3.59, range: [0, 10] },
    scale: { value: 61.07, range: [0, 100] },
    speed: { value: 0.66, range: [0, 1] },
    zindex: { value: 0, range: [-9999999, 9999999] },
    aspect: { value: 1.6071484375 },
    ignoreShapeAspect: { value: true },
    shapePosition: { value: { x: 0, y: 0 } },
    shapeScale: { value: { x: 0.5, y: 0.5 } },
    shapeEdgeSoftness: { value: 0, range: [0, 0.5] },
    shapeRadius: { value: 0, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: true },
    infiniteGooey: { value: true },
    growSize: { value: 4.53, range: [1, 15] },
    durationOut: { value: 1.3, range: [0.1, 5] },
    durationIn: { value: 1.71, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.12, range: [1, 5] },
    scrollType: { value: 0 },
    geoVertex: { range: [1, 64], value: 1 },
    noEffectGooey: { value: true },
    onMouse: { value: 0 },
    noise_speed: { value: 0.84, range: [0, 10] },
    metaball: { value: 0.11, range: [0, 2] },
    discard_threshold: { value: 0.54, range: [0, 1] },
    antialias_threshold: { value: 0.01, range: [0, 0.1] },
    noise_height: { value: 0.47, range: [0, 2] },
    noise_scale: { value: 18.32, range: [0, 100] },
  },
});
